### ISSUE TITLE
write a reusable widget for displaying text with different sizes in the app

### ISSUE THREAD

**Issue by nathansdev** [fidisys/hacktoberfest-flutter-app#2]
The current app displays "hacktoberfest 2019" in different sizes.
Write a reusable widget which accepts params (text, size) to show the text.

**Comment by payam-zahedi** [comment]
hi @nathansdev, I would like to work on it. please tell me about custom fields that u want to add to this widget.

**Comment by payam-zahedi** [comment]
and please tell me what widget name suppose to be?

**Comment by nathansdev** [comment]
Its can be simple as "ReusableText" @payam-zahedi .  custom fields 1.text, 2.size
